[package]
name = "huiyu-db-mapper-oracle11g"
version = {workspace = true}
edition = {workspace = true}
authors = {workspace = true}
build = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
description = {workspace = true}
readme = {workspace = true}
keywords = {workspace = true}
license = { workspace = true }
repository = {workspace = true}

[dependencies]
huiyu-db-mapper-core = { workspace = true }
tokio = { workspace = true}
chrono = {workspace = true}
tracing = {workspace = true}
oracle = {workspace = true}
rust_decimal = { workspace = true }
r2d2 = "0.8.10"
r2d2-oracle = { version = "0.7.0", features = ["chrono"] }
